#!/usr/bin/python3
import sys

if len(sys.argv) != 2:
    print("Bad Usage\n/.factors filename")
else:

    file_name = sys.argv[1]
    file_of_number = open(file_name)
    number = file_of_number.readline()

    while number != "\n" and number != "":
        number = int(number)
        divisor = 2
        while number % divisor != 0:
            divisor += 1
        d_r = int(number / divisor)
        print(f"{number}={d_r}*{divisor}")
        number = file_of_number.readline()
